// This file was generated by the XState CLI, please do not edit it manually.
import { assign, createMachine } from 'xstate';

const machine = createMachine(
  {
    context: {
      count: 0,
    },
    id: 'Counter',
    initial: 'idle',
    states: {
      idle: {
        on: {
          increment: {
            target: 'idle',
            actions: assign({ count: ({ context }) => context.count + 1 }),
          },
          reset: {
            target: 'idle',
            actions: assign({ count: 0 }),
          },
          decrement: {
            target: 'idle',
            actions: assign({ count: ({ context }) => context.count - 1 }),
          },
        },
      },
    },
    types: {
      events: {} as
        | { type: 'reset' }
        | { type: 'decrement' }
        | { type: 'increment' },
      context: {} as { count: number },
    },
  },
  {
    actions: {},
    actors: {},
    guards: {},
    delays: {},
  },
);
export const skyConfig = {
  actorId: '2841c899-6f04-4eca-b003-72fa1cf5db46',
  machine,
};
